---
- name war collector
  hosts: col
  become: yes

  tasks:
    - name: update apt cache
      apt: update_cache=true

    - name: Install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - default-jdk
        - maven
        - git

    - name: clone boxfuse
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse-sample-java-$
      tags: deploy
   
    - name: package boxfuse war
      command: mvn package -f /home/boxfuse-sample-java-war-hello

    - name: Copy WAR
      fetch:
        src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: ./hello-1.0.war
        flat: true

- name: war web prod
  hosts: web 
  become: yes

  tasks:
    - name: Ensure tomcat package is present
      apt: pkg=tomcat8 state=latest update_cache=yes

    - name: Copy WAR
      copy:
        src: ./hello-1.0.war
        dest: /var/lib/tomcat8/webapps/hello-1.0.war